version: '3.8'

services:
  media-forwarder:
    image: ghcr.io/haswelldev/media-forwarder:latest
    container_name: media-forwarder
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - ./config:/app/config
    restart: unless-stopped
